version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: alogadget_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: alogadget
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alogadget_net

  redis:
    image: redis:7-alpine
    container_name: alogadget_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alogadget_net

volumes:
  postgres_data:
  redis_data:

networks:
  alogadget_net:
    driver: bridge